#!/usr/bin/env php
<?php

require file_exists(__DIR__.'/vendor/autoload.php') ?  __DIR__.'/vendor/autoload.php' : __DIR__.'/../../autoload.php';

use Mehedi\BcryptCommand\Commands\MakeCommand;
use Symfony\Component\Console\Application;

define('BC_VERSION', '0.0.1');


$app = new Application('Bcrypt command line tool', BC_VERSION);


$app->add(new MakeCommand());

$app->run();